Delete entry & Comments
D-D-EINA-Calendar/CalendarServer pull request #69
Opened 2021-11-04 17:42 UTC by dolansete

2021-11-16 10:35 UTC, arejula27 requested changes
Pon los comentarios en inglés, en general las funciones no se entienden que hacen sin leer el codigo, haz una descripcion mas detallada y escoge un poco mjr lso nombres que alguna no se entiende. HAz más casos de test y tmb escoge mjr sus nombres ¿Qué es basic test? Mueve el archivo de test a la carpeta con la impl

2021-11-16 10:35 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +	//Select
Pon más info del select (campos que saca o algo así)

2021-11-16 10:35 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +	//Sacamos idaula para el entry
USa cammelCase que sino no se entienda

2021-11-16 10:35 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +func (repo *repo) DeleteEntry(entry domain.Entry) (error){
Describe las funciones

2021-11-16 10:35 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +func (repo *repo) updateHours(ini, fin domain.Hour, idhora int, create bool) (error){
updateHours is a function which change ... given ...

2021-11-16 10:35 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
> +		assert.Equal(t, true, true)
xdddd ya que hay cosas que revisar cambia esto haha

2021-11-21 11:26 UTC, dolansete commented on src/internal/repositories/horarioRepositorio_test.go
> +		assert.Equal(t, true, true)
Los tests estan arreglados en la otra PR

2021-11-21 19:31 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
> +		assert.Equal(t, true, true)
bru

2021-11-21 19:32 UTC, arejula27 approved these changes

2021-11-21 19:32 UTC, merged