Borrado PerteneceA y actualización y mejora de tests
D-D-EINA-Calendar/CalendarServer pull request #81
Opened 2021-11-20 18:24 UTC by dolansete

2021-11-20 19:06 UTC, arejula27 requested changes
HAy cambios de otro pr, corrige primero el primero y luego este para no corregirte todo 2 veces

2021-11-20 19:06 UTC, arejula27 commented on src/internal/core/domain/domain.go
> +
Esto no esta en otro pr?

2021-11-21 19:32 UTC, arejula27 commented on .github/workflows/go.yml
> +
vaya ttan

2021-11-21 19:35 UTC, arejula27 submitted a review, later dismissed
los comentarios estan en español, si acepto esta t hara override d lo k has cambiao :c 🌵

2021-11-21 23:16 UTC, dolansete commented on .github/workflows/go.yml
> +
Titan homosexual de las montañas

2021-11-21 23:17 UTC, dolansete commented on src/internal/core/domain/domain.go
> +
PUEDE SER SJSJSJSASJSASJ

2021-11-22 09:38 UTC, arejula27 requested changes
Tienes anotaciones por ahi pero a los test le faltan muchos casos, no compruebas si falta algun atrubuto y no hay test para casoso de error. En core el comportamiento depende si da error o no el repo por lo k es importante estar seguros de cuando va a dar y cuando no. Además mueve el ficher de test a la carpeta con la impl del repo.

2021-11-22 09:38 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +
español

2021-11-22 09:38 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
> +
Mejor nombre y descripción, ademas esta en español

2021-11-22 09:38 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
> +	assert.Equal(t, repos.EntryFound(entryAsked), true)
Solo se comprueba que funciona bien un caso, no compruebas que pasa si cada parámetro esta vacío

2021-11-22 09:38 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
>  func TestCreateEntryProb(t *testing.T) {
Faltan casos

2021-11-22 09:38 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio_test.go
>  func TestDeleteEntry(t *testing.T) {
Faltan casos

2021-11-22 09:38 UTC, arejula27 commented on src/pkg/sql/Create_Tables.sql
>      id int PRIMARY KEY AUTO_INCREMENT,
Pon los nombres en mayus si has puesto todo en mayus haha

2021-11-22 09:44 UTC, dolansete commented on src/pkg/sql/Create_Tables.sql
>      id int PRIMARY KEY AUTO_INCREMENT,
Es que creo que es case sensitive, dejo por si acaso las cosas de tablas en minúscula y así además es mas legible

2021-11-26 15:16 UTC, arejula27 requested changes

2021-11-26 15:16 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +		if entry.Week == "" || &entry.Week == nil {
No usas numeros magicos tienes constantes

2021-11-26 15:16 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio.go
> +		if entry.Group == "" || &entry.Group == nil {
same

2021-11-26 15:16 UTC, arejula27 commented on src/internal/repositories/horarioRepositorio/horarioRepositorio_test.go
> +func TestCreateEntryPract(t *testing.T) {
di lo k hace no lo k no ase

2021-11-26 15:16 UTC, arejula27 commented on src/pkg/apperrors/apperrors.go
>  )
invalid_subject_kind

2021-11-26 15:22 UTC, arejula27 approved these changes

2021-11-26 15:22 UTC, merged