Ya va que estaba pocho
D-D-EINA-Calendar/CalendarServer pull request #96
Opened 2021-12-03 10:01 UTC by dolansete

2021-12-07 20:22 UTC, arejula27 requested changes
te he mandado por wasap como se hace bien.

2021-12-07 20:22 UTC, arejula27 commented on docker-backend.sh
> +docker exec -it horarios_db bash -c "mysql -P 6033 -u user -puser app_db < /data/Populate_Tables.sql"
no se hace asi

2021-12-07 22:53 UTC, dolansete commented on docker-backend.sh
> +docker exec -it horarios_db bash -c "mysql -P 6033 -u user -puser app_db < /data/Populate_Tables.sql"
Hecho, muchas gracias

2021-12-08 13:49 UTC, arejula27 approved these changes
Ayer me dio un error al poblar de columna no existe, si ya va mergealo

2021-12-08 15:59 UTC, arejula27 requested changes
fallan los test no se por k

2021-12-08 16:54 UTC, arejula27 approved these changes

2021-12-08 16:59 UTC, merged